services:
  db:
    image: "postgres:18-alpine"
    container_name: personal_lib_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    networks:
      - personal_library
    restart: unless-stopped

volumes:
  db_data:

networks:
  personal_library:
    driver: bridge
